Regtest upgrade
i-pi/i-pi pull request #227
Opened 2022-08-12 10:59 UTC by litman90

Simple addition, to incorporate the possibility to define one tolerance value for all columns in NumPy data.

2022-08-12 11:32 UTC, ceriottm requested changes

2022-08-12 11:32 UTC, ceriottm commented on ipi_tests/regression_tests/runstools.py
> +                        listtol.append((float(info_tol[1]), float(info_tol[2])))
I think you should write it such that it also supports the case in which you have "all" without tolerances. It is a bit redundant, but it is more consistent with the structure when you can specify columns also with default tolerances

2022-08-12 11:32 UTC, ceriottm commented on ipi_tests/regression_tests/tests/NEB/FIRE/zundel/files_to_check.txt
> +ref_simulation.neb                      numpy       all,1.e-7,1e-6
I would also use the all syntax for the phonon case. There there are several checks on dynmat-like files with a load of columns, and I had only selected a random few. It's a great use case for `all`

2022-08-12 16:17 UTC, litman90 commented
I  think I applied all the requested changes, let me know if something else is required to merge this PR.

2022-08-13 06:39 UTC, ceriottm approved these changes

2022-08-13 06:39 UTC, merged