Cleaned up and improved the profiling code
i-pi/i-pi pull request #277
Opened 2023-10-06 20:20 UTC by ceriottm

Already used it to tweak a few bottlenecks, although actually there doesn't seem to be many. 
Also took the opportunity to polish a few examples, but would be probably better to do this in a separate branch so I'm stopping.

2023-10-17 11:18 UTC, mahrossi requested changes
Only minor, looks good overall. I would only require an example on how to run with profiling OR even better, an entry in the manual on how to profile the code.

2023-10-17 11:18 UTC, mahrossi commented on bin/i-pi
> +                      help='Type of profiling timing.')
Change to more descriptive? e.g. Profiling timing from cpu time or wallclock time.

2023-10-17 11:18 UTC, mahrossi commented on examples/features/Classical_molecular_dynamics/NPzT_ensemble_BZP/lammps_h2o_bulk_Ih/simulation.xc.pdb
Should this pdb file really be here? I think not

2023-10-17 15:51 UTC, venkatkapil24 commented
I am back from holiday, so I am available to take a look. But it would be great to have an example showing how to profile! Do we need a utility directory in examples?

2023-10-17 18:18 UTC, ceriottm commented on examples/features/Classical_molecular_dynamics/NPzT_ensemble_BZP/lammps_h2o_bulk_Ih/simulation.xc.pdb
No def. not.

2023-10-17 18:46 UTC, ceriottm commented
> I am back from holiday, so I am available to take a look. But it would be great to have an example showing how to profile! Do we need a utility directory in examples?

If you can add an example, that'd be great. I think it could belong to the `hpc_scripts` folder.  Let's discuss examples structure in a separate PR, there are several things I'd like to change there

2023-10-18 06:54 UTC, mahrossi commented on doc/src/troubleshooting.rst
> +   You will need to install the `yappi` profiler.
This is a great addition to the manual. Sorry to be pedantic, but for the user the actual command is needed. I thought one had to run `yappi i-pi ... `, but you suggest python -p i-pi? Just writing the command helps. then I would merge.

2023-10-19 04:15 UTC, merged