Demo for 2D-IR-Raman spectrum calculation using equilibrium-nonequilibrium RPMD
i-pi/i-pi pull request #279
Opened 2023-10-30 20:17 UTC by tbegusic

Includes a demo for running equilibrium-nonequilibrium RPMD with additional scripts in demos/2D-IR-Raman and a Fortran driver that computes induced dipole moment and polarizability of liquid water. @litman90

2023-10-31 18:00 UTC, litman90 commented
Thanks Tomislav, I will go over it in the following days

2023-11-07 16:47 UTC, litman90 requested changes
Everything is quite clear and easy to reproduce. 
I left some minor comments, please address them at your earliest convenience, add a short description to demos/README.md, and we will be ready to merge

2023-11-07 16:47 UTC, litman90 commented on demos/2D-IR-Raman/noneqm-traj.py
> +        help="Epsilon parameter controlling the field strength.",
Is this atomic units? Please specify

2023-11-07 16:47 UTC, litman90 commented on demos/2D-IR-Raman/README.md
> +where $lmp is the lammps executable. Note that i-pi-driver option water_dip_pol accepts one argument that is 1 if we want to compute dipole gradient or 0 if not.
I think dipole gradient here means dipole-z gradient, right? Please specify

2023-11-07 16:47 UTC, litman90 commented on demos/2D-IR-Raman/noneqm-traj.py
> +
Add here a job finished (without errors?) message

2023-11-07 16:47 UTC, litman90 commented on demos/2D-IR-Raman/noneqm-response.py
> +
Please add an exit message that species the name of the output file created

2023-11-07 16:47 UTC, litman90 commented on demos/2D-IR-Raman/noneqm-response.py
> +    )
Can you also explain here the output format, i.e. what are the rows and the columns?

2023-11-07 16:47 UTC, litman90 commented on demos/2D-IR-Raman/noneqm-response.py
> +            fmt="%.5e",
Please add header as comment line in the file

2023-11-17 23:16 UTC, tbegusic commented
Hi Yair, I believe I addressed all your comments. Please check and let me know if I missed something. Thank you!

2023-12-12 16:50 UTC, litman90 approved these changes

2023-12-12 16:54 UTC, litman90 approved these changes

2023-12-12 16:55 UTC, litman90 commented
Perfect, everything looks great.
I think I solved the conflict. If all the test past I will merge.
Thanks @tbegusic !

2023-12-12 17:01 UTC, merged